# Vagrantfile for Ubuntu 22.04 (ubuntu22/Vagrantfile)
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.network "forwarded_port", guest: 5432, host: 5439
  config.vm.provision "shell", path: "provision.sh", env: { "REPO" => ENV['REPO'] }
end
