#!/bin/bash
# Created by Roel Van de Paar, MariaDB

SAN_MODE=0
MYEXTRA_OPT="$*"
if [ "${1}" == "SAN" ]; then
  SAN_MODE=1
  MYEXTRA_OPT="$(echo "${MYEXTRA_OPT}" | sed 's|SAN||')"
fi

# Stop (if running), wipe and start all instances in parallel
if [ ${SAN_MODE} -eq 1 ]; then
  ./gendirs.sh SAN | xargs -I{} echo "cd {}; ./all_no_cl ${MYEXTRA_OPT}" | xargs -P50 -I{} sh -c "{}"
else
  ./gendirs.sh | xargs -I{} echo "cd {}; ./all_no_cl ${MYEXTRA_OPT}" | xargs -P50 -I{} sh -c "{}"
fi

sync
