#!/bin/bash
# Created by Roel Van de Paar, MariaDB

MYEXTRA_OPT="$*"

# Stop (if running), wipe and start all instances in parallel
./gendirs.sh | xargs -I{} echo "cd {}; ./all_no_cl ${MYEXTRA_OPT}" | xargs -P50 -I{} sh -c "{}"

sync
