#!/bin/bash
# Created by Roel Van de Paar, MariaDB

if [ ! -d ~/mariadb-qa ]; then                                                                        
  echo "Assert: this script expects ~/mariadb-qa to be present. Please do:"                           
  echo "cd ~ && git clone https://github.com/mariadb-corporation/mariadb-qa.git"                      
  exit 1                                                                                              
fi

TARGET=~/mariadb-qa/mariadb-build-qa
BUGS=~/mariadb-qa/BUGS
mkdir -p ${TARGET}
SCRIPT_PWD="$(cd `dirname $0` && pwd)"

cd ${SCRIPT_PWD}
cp buildall_dbg.sh ${TARGET}
cp buildall_opt.sh ${TARGET}
cp buildall_asan.sh ${TARGET}
cp clone.sh ${TARGET}
cp cloneall.sh ${TARGET}
cp copy_in.sql_all ${TARGET}
cp backup_github ${TARGET}
cp count_all ${TARGET}
cp findbug ${TARGET}
cp findbug+ ${TARGET}
cp gendirs.sh ${TARGET}
cp kill_all ${TARGET}
cp kill_ge ${TARGET}
cp kill_pr ${TARGET}
cp kill_s ${TARGET}
cp stop_all ${TARGET}
cp start_all ${TARGET}
cp startup_all ${TARGET}
cp all_all ${TARGET}
cp sge_all ${TARGET}
cp clean_all ${TARGET}
cp multi_sr_all ${TARGET}
cp dbg ${TARGET}
cp opt ${TARGET}
cp test_all ${TARGET}
cp find_cores ${TARGET}
cp untar ${TARGET}
cp prep_ram ${TARGET}
cp copy_all_tests ${TARGET}
cp check ${TARGET}
cp count_reducers ${TARGET}
cp qcdiffs ${TARGET}
cp pull_and_build_galera ${TARGET}
cp del_all_data ${TARGET}
cp loop_screens ${TARGET}
cp loop_screens_ge ${TARGET}
cp loop_screens_pr ${TARGET}
cp monitor_run ${TARGET}
cp monitor_runs ${TARGET}
cp todaysruns ${TARGET}
cp allruns ${TARGET}
cp scan_MYBUG ${TARGET}
cp linkit ${TARGET}
cp REGEX_EXCLUDE ${TARGET}
cp find_deadlocks ${TARGET}
cp prep_ram_full ${TARGET}
cp REGEX_EXCLUDE ${TARGET}
cp use_new ${TARGET}
cp use_old ${TARGET}

cd ${TARGET}
git add *
cd ${BUGS}
git add *.sql
