#!/bin/bash
# Created by Roel Van de Paar, MariaDB

TARGET=~/mariadb-qa/mariadb-build-qa
mkdir -p ${TARGET}
SCRIPT_PWD="$(cd `dirname $0` && pwd)"

cd ${SCRIPT_PWD}
cp buildall_dbg.sh ${TARGET}
cp buildall_opt.sh ${TARGET}
cp clone.sh ${TARGET}
cp cloneall.sh ${TARGET}
cp copy_in.sql_all ${TARGET}
cp backup_github ${TARGET}
cp count_all ${TARGET}
cp findbug ${TARGET}
cp findbug+ ${TARGET}
cp gendirs.sh ${TARGET}
cp kill_all ${TARGET}
cp stop_all ${TARGET}
cp start_all ${TARGET}
cp startup_all ${TARGET}
cp all_all ${TARGET}
cp dbg ${TARGET}
cp opt ${TARGET}
cp test_all ${TARGET}
cp find_cores ${TARGET}
cp untar ${TARGET}
cp prep_ram ${TARGET}
cp copy_all_tests ${TARGET}
cp check ${TARGET}

cd ${TARGET}
git add *
cd ~/mariadb-qa/BUGS
git add MDEV*.sql
