cd 10.1
~/mariadb-qa/build_mdpsms_opt_asan.sh &
cd ../10.2
~/mariadb-qa/build_mdpsms_opt_asan.sh &
cd ../10.3
~/mariadb-qa/build_mdpsms_opt_asan.sh &
cd ../10.4
~/mariadb-qa/build_mdpsms_opt_asan.sh &
cd ../10.5
~/mariadb-qa/build_mdpsms_opt_asan.sh &
