#!/bin/bash

REGEX_EXCLUDE="$(cat REGEX_EXCLUDE 2>/dev/null)"  # Handy to exclude a particular build
if [ -z "${REGEX_EXCLUDE}" ]; then REGEX_EXCLUDE="DUMMYSTRINGNEVERSEEN"; fi

FIRST=$(./gendirs.sh 2>/dev/null | wc -l)
SECON=$(ls --color=never */bin/mysqld 2>/dev/null | grep -vE "${REGEX_EXCLUDE}" | grep -vE "SAN|GAL" | wc -l)
THIRD=$(ls --color=never */bin/mysql 2>/dev/null | grep -vE "${REGEX_EXCLUDE}" | grep -vE "SAN|GAL" | wc -l)
FOURT=$(ls --color=never */all 2>/dev/null | grep -vE "${REGEX_EXCLUDE}" | grep -vE "SAN|GAL" | wc -l)

if [ ${FIRST} -eq ${SECON} -a ${FIRST} -eq ${THIRD} -a ${FIRST} -eq ${FOURT} ]; then
  echo "All OK"
  exit 0
else
  echo "Mismatch!"
  echo "Number of directories reported by gendirs.sh; ${FIRST}"
  echo "Number of directories which have bin/mysqld ; ${SECON}"
  echo "Number of directories which have bin/mysql  ; ${THIRD}"
  echo "Number of directories which have all        ; ${FOURT}"
  exit 1
fi
