#!/bin/bash
set +H
if [ ! -r ~/mariadb-qa/known_bugs.strings ]; then echo '~/mariadb-qa/known_bugs.strings not found!'; exit 1; fi
if [ ! -d /data/NEWBUGS -a ! -d /data/FIREWORKS ]; then echo '/data/NEWBUGS and /data/FIREWORKS not found!'; exit 1; fi
# This needs some work:
# Done! (Newbugs 014)
# bash: -c: line 0: syntax error near unexpected token `>|'
# bash: -c: line 0: `rm list.count > 0|SIGABRT|ut_dbg_assertion_failed|ut_list_remove<ut_list_base<buf_page_t, ut_list_node<buf_page_t> buf_page_t::*>, GenericGetNode<buf_page_t> >|ut_list_remove<ut_list_base<buf_page_t, ut_list_node<buf_page_t> buf_page_t::*> >|buf_flush_relocate_on_flush_list'
# Done! (Newbugs 015)
# Disabled ftm. Test manually, fix may be to change '>|' to '\>\|' or similar?
# Also, this code is slow. The one below is much quicker, but only works on a limited subset.
# Perhaps a better idea is to move into dirs and then run below code on subdirs?
#for DIR in $(seq 1 999); do
#  if [ ${DIR} -le 9 ]; then
#    DIR2="00${DIR}"
#  elif [ ${DIR} -le 99 ]; then
#    DIR2="0${DIR}"
#  else
#    DIR2="${DIR}"
#  fi
#  if [ ! -z "$(ls /data/NEWBUGS/newbug_${DIR2}*.string 2>/dev/null)" ]; then
#    grep --binary-files=text -vE '^[ \t]*$|^#' ~/mariadb-qa/known_bugs.strings 2>/dev/null | sed 's|[ \t]\+##.*$||' | xargs -I{} grep --binary-files=text -Fi "{}" /data/NEWBUGS/newbug_${DIR2}*.string 2>/dev/null | sed 's|.string:.*$|.*|' | xargs -I{} echo "rm {}" | xargs -I{} bash -c "{}"
#    echo "Done! (Newbugs ${DIR2})"
#  fi
#done
grep --binary-files=text -vE '^[ \t]*$|^#' ~/mariadb-qa/known_bugs.strings 2>/dev/null | sed 's|[ \t]\+##.*$||' | xargs -I{} grep --binary-files=text -Fi "{}" /data/NEWBUGS/*.string 2>/dev/null | sed 's|.string:.*$|.*|' | xargs -I{} echo "rm {}" | xargs -I{} bash -c "{}"
echo 'Done! (Newbugs)'

grep --binary-files=text -vE '^[ \t]*$|^#' ~/mariadb-qa/known_bugs.strings 2>/dev/null | sed 's|[ \t]\+##.*$||' | xargs -I{} grep --binary-files=text -Fi "{}" /data/FIREWORKS/*.string 2>/dev/null | sed 's|.string:.*$|.*|' | xargs -I{} echo "rm {}" | xargs -I{} bash -c "{}"
echo 'Done! (Fireworks)'
