#!/bin/bash
set +H
if [ ! -r ~/mariadb-qa/known_bugs.strings ]; then echo '~/mariadb-qa/known_bugs.strings not found!'; exit 1; fi
if [ ! -d /data/NEWBUGS -a ! -d /data/FIREWORKS ]; then echo '/data/NEWBUGS and /data/FIREWORKS not found!'; exit 1; fi
grep --binary-files=text -vE '^[ \t]*$|^#' ~/mariadb-qa/known_bugs.strings 2>/dev/null | sed 's|[ \t]\+##.*$||' | xargs -I{} grep --binary-files=text -Fi "{}" /data/NEWBUGS/*.string 2>/dev/null | sed 's|.string:.*$|.*|' | xargs -I{} echo "rm {}" | xargs -I{} bash -c "{}"
echo 'Done! (Newbugs)'
grep --binary-files=text -vE '^[ \t]*$|^#' ~/mariadb-qa/known_bugs.strings 2>/dev/null | sed 's|[ \t]\+##.*$||' | xargs -I{} grep --binary-files=text -Fi "{}" /data/FIREWORKS/*.string 2>/dev/null | sed 's|.string:.*$|.*|' | xargs -I{} echo "rm {}" | xargs -I{} bash -c "{}"
echo 'Done! (Newbugs)'
