#!/bin/bash
# Created by Roel Van de Paar, MariaDB

REGEX_EXCLUDE="$(cat REGEX_EXCLUDE 2>/dev/null)"  # Handy to exclude a particular build
if [ -z "${REGEX_EXCLUDE}" ]; then REGEX_EXCLUDE="DUMMYSTRINGNEVERSEEN"; fi

SAN_MODE=0
if [ -z "${1}" ]; then
  echo "This script expects a bug search string as input, OR the word 'SAN' for *SAN runs with the environment variable TEXT pre-set."
  exit 1
elif [ "${1}" == "SAN" ]; then
  if [ -z "${TEXT}" ]; then   # Passed normally by ~/b, bug_report.sh, test_all and findbug+ scripts
    echo "Assert: TEXT is empty, use export TEXT= to set it!"
    exit 1
  fi
  SAN_MODE=1
fi

if [ ${SAN_MODE} -eq 1 ]; then
  grep -Ei --binary-files=text "${TEXT}" */log/master.err | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | grep --binary-files=text -E "SAN"
else
  grep -Ei --binary-files=text "${1}" */log/master.err | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | grep -vE --binary-files=text "SAN|GAL"
fi
