#!/bin/bash
# Created by Roel Van de Paar, MariaDB

if [ -z "${1}" ]; then
  echo "This script expects a bug search string as input, OR the word 'ASAN' for *SAN runs with the environment variable TEXT pre-set."
  exit 1
elif [ "${1}" == "ASAN" ]; then
  if [ -z "${TEXT}" ]; then   # Passed normally by ~/b, bug_report.sh, test_all and findbug+ scripts
    echo "Assert: TEXT is empty, use export TEXT= to set it!"
    exit 1
  fi
  ASAN_MODE=1
fi

if [ ${ASAN_MODE} -eq 1 ]; then
  grep "${TEXT}" */log/master.err | grep "ASAN"
else
  grep "${1}" */log/master.err | grep -vE "ASAN|GAL"
fi
