#!/bin/bash
# Created by Roel Van de Paar, MariaDB

# The ./kill script ensures the correct server datadir is selected by checking for '${PWD}/log/master.err' in the command line. Thus, mysqld's started by reducer.sh, pquery-run.sh and other scripts will not be affected as they use another location for the error log!

GENDIRS=gendirs.sh
if [ ! -r ./${GENDIRS} ]; then 
  if [ -r ../${GENDIRS} ]; then
    GENDIRS=../gendirs.sh
  else
    echo "./gendirs.sh not found!"
    exit 1
  fi
else 
  GENDIRS=./gendirs.sh 
fi

SAN=""
if [ "${1}" == "SAN" ]; then SAN="SAN"; fi
set +H
${GENDIRS} ${SAN} | xargs -I{} echo "cd {}; if [ -r ./kill ]; then ./kill; else echo './kill did not exist for directory {} - please run ./startup_all or instead do cd {}; ~/mariadb-qa/startup.sh; cd -'; fi; cd .." | xargs -P50 -I{} sh -c "{}"

sync
