#!/bin/bash

screen -d -r | grep "\.ge[0-9]\+" | sed 's|\..*||' | sed 's|[^0-9]||g' | sort -un > ~/screen_list_ge

COUNT=$(wc -l ~/screen_list_ge 2>/dev/null | sed 's| .*||')

for SCREEN in $(seq 1 ${COUNT}); do
  PID="$(head -n ${SCREEN} ~/screen_list_ge | tail -n1)"
  echo "Connecting you to screen ${SCREEN}/${COUNT} with PID ${PID}"
  screen -d -r ${PID}
done

rm -f ~/screen_list_ge
