#!/bin/bash

ACTUAL_FILTER="$(grep -m1 "BASEDIR.*SAN" */pquery-pquery-run-MD105.conf | sed 's|/.*||' | tr '\n' '|' | sed 's/|$/\n/')"

if [ -z "${1}" ]; then
  ~/ooo | grep -vE "LOG_WITH_COREDUMP|VARIOUS_BUILDS|MONTY|ANALYZE_LATER_FAILS_REPROD" | grep "^[ ]\+[0-1 ][0-9 ][0-9] " | sort -nr | grep -E "[ \t]${ACTUAL_FILTER}/"
else
  ~/ooo | grep -vE "LOG_WITH_COREDUMP|VARIOUS_BUILDS|MONTY|ANALYZE_LATER_FAILS_REPROD" | grep "^[ ]\+[0-1 ][0-9 ][0-9] " | sort -nr | awk '{print $2}' | xargs -I{} grep --binary-files=text -L 'mysqld options required' {} | xargs -I{} wc -l {} | grep -E --binary-files=text "[ \t]${ACTUAL_FILTER}/"
fi
