#!/bin/bash

if [ "${_}" == "${0}" ]; then
  echo "Source me instead! Like this:"
  echo ". ./scriptname"
  exit 1
fi

REGEX_EXCLUDE="$(cat REGEX_EXCLUDE 2>/dev/null)"  # Handy to exclude a particular build
cd $(ls -d MD[0-9][0-9][0-9][0-9][0-9][0-9]-mariadb-10.5.*-linux-x86_64-opt | grep -vE "${REGEX_EXCLUDE}")
