#!/bin/bash

# User variables
VERSION="10.5"

# Script variables
BASEDIR="$(ls -d MD*${VERSION}* 2>/dev/null | sed 's|-[do][bp][gt]||' | sort -ur | head -n1)"   # without -opt and -dbg

if [ -z "${BASEDIR}" ]; then
  echo "Assert: BASEDIR is empty!"
  exit 1
fi

if [ ! -r ~/ramdrive.sh ]; then
  echo "Assert: ~/ramdrive.sh missing, you likely want to do something like:"
  echo "cp ~/mariadb-qa/homedir_scripts/* ~"
  exit 1
fi

if [ ! -z "$(mount | grep ramfs)" ]; then
  ~/ramdrive.sh
  if [ ! -z "$(mount | grep ramfs)" ]; then
    echo "Assert: ram drive creation failed!"
    exit 1
  fi
fi

cp -r ${BASEDIR}-opt /ram
cp -r ${BASEDIR}-dbg /ram
cd /ram/${BASEDIR}-opt
~/mariadb-qa/startup.sh
cd /ram/${BASEDIR}-dbg
~/mariadb-qa/startup.sh
echo "cd ${BASEDIR}-opt" > /ram/opt
echo "cd ${BASEDIR}-dbg" > /ram/dbg
