#!/bin/bash
# Created by Roel Van de Paar, MariaDB

# ONLY RUN THIS SCRIPT ON A NON-PRODUCTION SERVER, IT MOVES /etc/mysql to /etc/mysql.old

if [ ! -r ~/mariadb-qa/startup.sh ]; then
  echo "Assert: incorrect infrastructure setup! Please make ~/mariadb-qa/startup.sh to be available"
  exit 1
fi

./gendirs.sh | xargs -I{} echo "cd {}; ~/mariadb-qa/startup.sh; cd .." | xargs -P50 -I{} sh -c "{}"

sync

sudo mv /etc/mysql /etc/mysql.old   # Avoids any local my.cnf from being used by any mysqld

echo "Complete! The information above (on ./all) refers to the script which were created INSIDE the base directories, i.e. you can do: cd somebasedir; ./all"
