#!/bin/bash
# Created by Roel Van de Paar, Percona LLC

# ====== Internal Variables: do not modify
SCRIPT_PWD=$(cd `dirname $0` && pwd)

# ====== User Variables
# The file generated by generator.sh, usually ${SCRIPT_PWD}/out.sql if you used generator.sh in the same directory as this script
  GENERATED_SQL_FILE=${SCRIPT_PWD}/out.sql
# The file obtained by executing ./bin/mysql -A -uroot -S./socket.sock --force --binary-mode test < ~/percona-qa/generator/out.sql > out.txt 2>&1
  CLI_OUTPUT_FILE=/sda/Percona-Server-5.7.13-6-Linux.x86_64.ssl101/out.txt

grep "You have an error.*SQL" ${CLI_OUTPUT_FILE} | \
  grep -o " at line [0-9]\+: " | \
  grep -o "[0-9]\+" | \
  xargs -I{} sed -n "{}p" ${GENERATED_SQL_FILE} | \
  more
