DROP DATABASE test;CREATE DATABASE test;USE test;
DELIMITER //
CREATE PROCEDURE dorepeat()
  LOOP
    SQL_STATEMENTS;
    SQL_STATEMENTS;
    SQL_STATEMENTS;
  END LOOP
//
DELIMITER ;
CALL dorepeat();
