#INSTALL PLUGIN adt_null SONAME 'adt_null.so';                                        # NO
#INSTALL PLUGIN dialog SONAME 'dialog.so';                                            # NO
#INSTALL PLUGIN qa_auth_interface SONAME 'qa_auth_interface.so';                      # NO
#INSTALL PLUGIN qa_auth_client SONAME 'qa_auth_client.so';                            # NO
#INSTALL PLUGIN qa_auth_server SONAME 'qa_auth_server.so';                            # NO
#INSTALL PLUGIN mypluglib SONAME 'mypluglib.so';                                      # NO
#INSTALL PLUGIN test_security_context SONAME 'test_security_context.so';              # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_shutdown.so';                                   # NO
#INSTALL PLUGIN ? SONAME 'libtest_services.so';                                       # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_all_col_types.so';                              # NO
#INSTALL PLUGIN ? SONAME 'libtest_session_detach.so';                                 # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_processlist.so';                                # NO
#INSTALL PLUGIN ? SONAME 'libtest_x_sessions_deinit.so';                              # NO
#INSTALL PLUGIN ? SONAME 'libtest_services_threaded.so';                              # NO
#INSTALL PLUGIN ? SONAME 'libtest_session_in_thd.so';                                 # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_commit.so';                                     # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_complex.so';                                    # NO
#INSTALL PLUGIN ? SONAME 'libtest_x_sessions_init.so';                                # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_lock.so';                                       # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_sqlmode.so';                                    # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_stored_procedures_functions.so';                # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_2_sessions.so';                                 # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_errors.so';                                     # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_cmds_1.so';                                     # NO
#INSTALL PLUGIN ? SONAME 'libtest_framework.so';                                      # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_replication.so';                                # NO
#INSTALL PLUGIN ? SONAME 'libtest_session_info.so';                                   # NO
#INSTALL PLUGIN ? SONAME 'libtest_sql_views_triggers.so';                             # NO
#INSTALL PLUGIN ? SONAME 'libfnv_udf.so';                                             # NO
#INSTALL PLUGIN ? SONAME 'auth_test_plugin.so';                                       # NO
#INSTALL PLUGIN libdaemon_example SONAME 'libdaemon_example.so';                      # NO
#INSTALL PLUGIN ha_example SONAME 'ha_example.so';                                    # NO
#INSTALL PLUGIN ? SONAME 'replication_observers_example_plugin.so';                   # NO
#INSTALL PLUGIN rewrite_example SONAME 'rewrite_example.so';                          # NO (interesting for future QA: rewrite queries as subqueries etc.)
