#!/bin/bash
# Created by Roel Van de Paar, Percona LLC

TRIAL=$(echo "$1" | sed 's|_val||' | sed 's|[ \t]*||g')  # _val: for Valgrind bugs (reducer_val{trial}.sh generated by pquery-prep-red.sh)
if [ "${TRIAL}" == "" ]; then
  echo "This script deletes a given pquery trial completely. Execute this script from within the pquery workdir"
  echo "Example: to delete trial 10 (./10), execute as: ./delete_single_trial.sh 10"
  exit 1
elif [ "`echo ${TRIAL} | sed 's|[0-9]*||'`" != "" ]; then
  echo "Trial number should be a numeric value and isn't (value passed to this script which is not considered numeric: '${TRIAL}')"
  exit 1
elif [ -d ./${TRIAL} ]; then
  # Delete trial directory
  rm -Rf ./${TRIAL} > /dev/null 2>&1
else
  echo "This script deletes a given pquery trial completely. Execute this script from within the pquery workdir"
  echo "Error: trial number '${TRIAL}' was passed as an option to this script. However, no trial ${TRIAL} directory (./${TRIAL}) exists!"
  echo "Will still attempt to delete all related remaining files, if any"
fi

# Delete other files
rm -f  ./reducer${TRIAL}.sh > /dev/null 2>&1
rm -f  ./reducer_val${TRIAL}.sh > /dev/null 2>&1
rm -f  ./reducer${TRIAL}-*.sh > /dev/null 2>&1
rm -f  ./${TRIAL}_bundle > /dev/null 2>&1
rm -f  ./${TRIAL}_bundle.tar.gz > /dev/null 2>&1

echo "- pquery trial #${TRIAL} and all related files wiped"
