#!/bin/bash
# Created by Ramesh Sivaraman, Percona LLC

echoit(){
  echo "[$(date +'%T')] $1"
}

# User configurable variables
BASEDIR="/home/vagrant/postgresql-10.3"   # Postgress source directory (should contain src directory as a first level subdirectory, see TESTS_PATH)

FINAL_SQL=/tmp/ptr_to_sql.sql   # pquery final SQL grammar (i.e. file name for output generated by this script)
rm -rf $FINAL_SQL

TESTS_PATH=$(echo ${BASEDIR} | sed 's|$|/src|;s|//||g')

if [[ $(ls $TESTS_PATH/test/regress/sql/*.sql 2>/dev/null | wc -l ) -eq 0 ]]; then
  echoit "Assert: this script cannot locate sql files in ${TESTS_PATH}/test/regress/sql"
  exit 1
fi

echoit "> Generating SQL"

cat $TESTS_PATH/test/*/*.sql $TESTS_PATH/test/*/*/*.sql $TESTS_PATH/test/*/*/*/*.sql | \
  sed '/^$/d' | \
  sed '/^--.*/d' | \
  sed 's|;.*.\-\-.*|;|' | \
  sed '/^\\d/d' | \
  sed -e :x -e '/;$/b' -e N -e 's/\n//' -e bx | \
  sed 's|/\*.*.\*/||' | \
  sed 's|\\echo.*.\\quit||' >> $FINAL_SQL

echoit "Done! Generated ${FINAL_SQL}"
