# Vagrantfile for Oracle Linux 9 (ol9/Vagrantfile)
Vagrant.configure("2") do |config|
  config.vm.box = "generic/oracle9"
  config.vm.network "forwarded_port", guest: 5432, host: 5436
  config.vm.provision "shell", path: "provision.sh", env: { "REPO" => ENV['REPO'] }
end
