DELIMITER ||
CREATE EVENT querytimeout ON SCHEDULE EVERY 20 SECOND DO BEGIN
SET @id:='';
SET @id:=(SELECT id FROM INFORMATION_SCHEMA.PROCESSLIST WHERE ID<>CONNECTION_ID() AND STATE<>'killed' AND TIME>$QUERYTIMEOUT ORDER BY TIME DESC LIMIT 1);
IF @id > 1 THEN KILL QUERY @id; END IF;
END ||
DELIMITER ;
