CREATE TABLE t1 (a INT);
CREATE TABLE t2 (b INT);
CREATE VIEW v2 AS SELECT * FROM t2 ;
LOCK TABLES t1 WRITE, v2 WRITE;
CREATE TABLE IF NOT EXISTS t1 LIKE t2;

USE test;
CREATE TABLE t1 (c INT);
CREATE TABLE t2 (c INT);
LOCK TABLES t1 WRITE,t2 WRITE;
CREATE TABLE IF NOT EXISTS t1 LIKE t2;
