SET SESSION max_heap_table_size=16384;
WITH RECURSIVE q (b) AS (SELECT 1 UNION ALL SELECT 1+b FROM q WHERE b<2000) SELECT MIN(q.b),MAX(q.b),AVG(q.b) FROM q, q AS q1;

USE test;
CREATE TABLE t (a INT) ROW_FORMAT=compressed, ENGINE=InnoDB;
ALTER TABLE t ADD COLUMN c2 INTEGER COMMENT 'a';
SET tmp_table_size=100;
INSERT INTO t  VALUES (94, 46), (31, 438), (61, 152), (78, 123), (88, 411), (122, 118), (0, 177), (75, 42), (108, 67), (79, 349), (59, 188), (68, 206), (49, 345);
SELECT * FROM ( SELECT * FROM t UNION SELECT * FROM t) a,(SELECT * FROM t UNION SELECT * FROM t) b;

USE test;
SET SQL_MODE='';
SET SESSION tmp_table_size=True;
CREATE TABLE t (f INT(10) UNSIGNED NOT NULL) ENGINE=InnoDB;
INSERT INTO t VALUES (CONVERT(_ucs2 0x062F06390648062A0650 USING utf8));
insert INTO t SELECT REPEAT('abcdefghijklmnopqrstuvwxyz',100);
INSERT INTO t VALUES(0xAAB6);
CREATE TEMPORARY TABLE t (e INT, f INT, PRIMARY KEY (f)) ENGINE=InnoDB;
SET SESSION OPTIMIZER_SWITCH="derived_merge=OFF";
DROP TABLE t;
SELECT 1 FROM ((SELECT * FROM (SELECT * FROM t) AS a) AS a, (SELECT * FROM t) AS b);

# MDEV-22104
SET max_heap_table_size= 1048576;
CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (1),(2);
CREATE TABLE t2 (a INT,  b INT, c VARCHAR(3), d VARCHAR(35));
INSERT INTO t2 (a) SELECT seq FROM seq_1_to_130;
SET optimizer_switch = 'derived_merge=off';
SELECT * FROM t1, ( SELECT t2a.* FROM t2 AS t2a, t2 AS t2b ) AS sq;
