USE test;
SET default_storage_engine=MyISAM;
SET SESSION alter_algorithm=4;
CREATE TABLE t(a INT) PARTITION BY RANGE(a) SUBPARTITION BY KEY(a) (PARTITION p0 VALUES LESS THAN (10) (SUBPARTITION s0,SUBPARTITION s1), PARTITION p1 VALUES LESS THAN (20) (SUBPARTITION s2,SUBPARTITION s3));
ALTER TABLE t ADD COLUMN c INT;
