# Sporadic, execute about 200 times
DROP DATABASE test;
CREATE DATABASE test;
USE test;
SET SQL_MODE='';
CREATE TABLE t (a INT(11) DEFAULT NULL, b INT(11) DEFAULT NULL, c INT(11) GENERATED ALWAYS AS (a+b) VIRTUAL, x INT(11) NOT NULL, h VARCHAR (10) DEFAULT NULL, KEY idx (c)) DEFAULT CHARSET=latin1;
INSERT INTO t VALUES (1,54,"zardosht", 'abcdefghijklmnopqrstuvwxyz', 3287);
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT a FROM t WHERE b is NULL and c is NOT NULL ORDER BY a;

CREATE TABLE t1 (a INT, b INT, c INT, v INT AS (a) VIRTUAL, INDEX(c,v)) ENGINE=InnoDB;
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
INSERT INTO t1 (c) VALUES (9);
SELECT * FROM t1 WHERE c BETWEEN 1 AND 6 ORDER BY b;
