CREATE TABLE t1 (i INT NOT NULL, KEY (i)) ROW_FORMAT=DYNAMIC PARTITION BY KEY(i) PARTITIONS 2;
CREATE TABLE t2 (i INT NOT NULL, KEY (i));
ALTER TABLE t1 EXCHANGE PARTITION p1 WITH TABLE t2;

SET SQL_MODE='';
CREATE TABLE t1 (a INT, b VARCHAR(55), PRIMARY KEY(a)) ENGINE=InnoDB PARTITION BY RANGE (a) (PARTITION p0 VALUES LESS THAN (10), PARTITION p1 VALUES LESS THAN (100), PARTITION p2 VALUES LESS THAN (1000));
CREATE TABLE t2 (a INT, b VARCHAR(55), PRIMARY KEY(a)) CHECKSUM=1, ENGINE=InnoDB;
ALTER TABLE t1 EXCHANGE PARTITION p0 WITH TABLE t2;
