USE test;
CREATE TABLE t (a CHAR(198));
ALTER TABLE t CHANGE COLUMN a a CHAR(220) BINARY;
ALTER TABLE t ADD COLUMN b INT FIRST;

CREATE TABLE t1 (a TEXT CHARSET utf8, b INT) ENGINE=InnoDB CHARSET utf8mb4;
ALTER TABLE t1 MODIFY a TEXT AFTER b;

USE test;
CREATE TABLE t (a TEXT,b CHAR(255) PRIMARY KEY) CHARSET=utf8;
SET GLOBAL innodb_default_row_format = 0;
ALTER TABLE t ADD COLUMN c INT FIRST;

USE test;
CREATE TABLE t (c CHAR(255), PRIMARY KEY (c)) CHARSET=utf8;
ALTER TABLE t ADD COLUMN b INT FIRST;
SET GLOBAL INNODB_DEFAULT_ROW_FORMAT = 0;
ALTER TABLE t ADD COLUMN a INT FIRST;
