USE test;
SET @@SESSION.max_sort_length=5;
CREATE TABLE t(c TIME(6));
INSERT INTO t VALUES ('00:00:00');
UPDATE t SET c='00:00:00' ORDER BY c;

SET @@SESSION.max_sort_length=5;
CREATE OR REPLACE TABLE t1(c TIME(6));
INSERT INTO t1 VALUES ('00:00:00');
SELECT * FROM t1 ORDER BY c;
