USE test;
CREATE TABLE t(c1 INT,KEY(c1))ENGINE=InnoDB;
INSERT INTO t VALUES(55997),(3942);
ALTER TABLE t ENGINE=Aria;
SET GLOBAL aria_encrypt_tables=1;
REPAIR TABLE t USE_FRM;
REPAIR TABLE t USE_FRM;
