USE test;
CREATE TABLE t (a INT KEY);
HANDLER t OPEN AS t;
XA START '0';
SELECT * FROM t;
XA END '0';
XA PREPARE '0';
HANDLER t READ NEXT;

CREATE TABLE t (i INT);
CREATE TABLE t2 (a INT, KEY(a));
XA BEGIN 'x';
SELECT DATE_SUB(a, INTERVAL 1 MINUTE) FROM t2 ORDER BY a;
HANDLER t OPEN;
XA END 'x';
XA PREPARE 'x';
HANDLER t READ FIRST;
