CREATE EVENT e ON SCHEDULE EVERY 5 HOUR DO SELECT 2;
SET timestamp=100000000;
CREATE EVENT root8 ON SCHEDULE EVERY '2:5' YEAR_MONTH DO SELECT 1;
CREATE EVENT EVENT1 ON SCHEDULE EVERY 15 MINUTE STARTS NOW() ENDS DATE_ADD(NOW(), INTERVAL 5 HOUR) DO BEGIN END;
SET GLOBAL event_scheduler=TRUE;
ALTER EVENT e ON SCHEDULE EVERY 1 HOUR STARTS '1999-01-01 00:00:00';
DROP PROCEDURE not_there;
DROP EVENT IF EXISTS non_existing;
