CREATE TABLE t1 (t TIMESTAMP NOT NULL) ENGINE=MyISAM;
SELECT * FROM t1 WHERE TRUNCATE( t, 1 );

CREATE OR REPLACE TABLE t1 (t TIMESTAMP NOT NULL) ENGINE=MyISAM;
SELECT * FROM t1 WHERE TRUNCATE( t, 1 );

USE test;
CREATE TABLE t (a TIMESTAMP,b TIMESTAMP);  # (ENGINE=InnoDB) 
INSERT INTO t VALUES (0,0);
SET SQL_MODE='TRADITIONAL';
SELECT TRUNCATE(a,b) AS c FROM t;
