DROP DATABASE test;
CREATE DATABASE test;
USE test;
SET GLOBAL innodb_limit_optimistic_insert_debug=2;
SET GLOBAL innodb_immediate_scrub_data_uncompressed=ON;
CREATE TABLE t (c INT) ENGINE=InnoDB;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;
TRUNCATE t;  # More if needed

USE test;
CREATE TABLE ti (a TINYINT NOT NULL, b SMALLINT, c CHAR(87) NOT NULL, d VARCHAR(73) NOT NULL, e VARCHAR(19), f VARCHAR(98) NOT NULL, g TINYBLOB, h BLOB NOT NULL, id BIGINT NOT NULL, KEY(b), KEY(e), PRIMARY KEY(id)) ENGINE=RocksDB;
SET @@GLOBAL.OPTIMIZER_SWITCH="index_merge_intersection=ON";
set global innodb_limit_optimistic_insert_debug = 2;
CREATE TABLE `龗龗龗`(`丄丄丄` char(1)) DEFAULT CHARSET = utf8 engine=RocksDB;
create table t4 (id int primary key) engine = TokuDB key_block_size = 2;
set global innodb_immediate_scrub_data_uncompressed=ON;
CREATE TABLE t1 (col_longtext_ucs2 longtext, col_longtext_utf8 longtext, col_varchar_255_ucs2_key varchar(255), col_set_utf8 set ('a','b'), col_char_255_ucs2 char(255), col_char_255_ucs2_key char(255), col_enum_ucs2 enum ('a','b'), col_varchar_255_ucs2 varchar(255), col_longtext_ucs2_key longtext, col_longtext_utf8_key longtext, col_enum_utf8 enum ('a','b'), col_varchar_255_utf8_key varchar(1024), col_varchar_255_utf8 varchar(255), col_enum_ucs2_key enum ('a','b'), col_enum_utf8_key enum ('a','b'), col_set_utf8_key set ('a','b'), col_char_255_utf8 char(255), pk integer auto_increment, col_set_ucs2_key set ('a','b'), col_char_255_utf8_key char(255), col_set_ucs2 set ('a','b'), primary key (pk)) ENGINE=InnoDB;
SELECT floor(cast(-2 as unsigned)), floor(18446744073709551614), floor(-2);
ALTER TABLE ti CHANGE COLUMN c c BINARY(69) NOT NULL;
TRUNCATE t1;
TRUNCATE t1;
TRUNCATE t1;
