CREATE TABLE t (a DECIMAL(10) PRIMARY KEY) ENGINE=InnoDB;
SELECT (SELECT SUM(t.a) FROM t x WHERE t.a = x.a) FROM t;

CREATE TABLE t (a INT NOT NULL AUTO_INCREMENT, b INT NOT NULL, c VARCHAR (11) NOT NULL, PRIMARY KEY(a), INDEX (b));
ALTER TABLE t MODIFY a DECIMAL(30,6), MODIFY b DECIMAL(30,6);
SET SQL_MODE=TRADITIONAL;
SELECT SQL_NO_CACHE (SELECT SUM(c.a) FROM t ttt, t ccc WHERE ttt.a = ccc.b AND ttt.a = t.a GROUP BY ttt.a) AS out FROM t t, t c WHERE t.a = c.b;
