USE test;
SET SQL_MODE='';
CREATE TABLE t (c DOUBLE PRECISION PRIMARY KEY) ENGINE=Memory;
INSERT INTO t VALUES (1);
REPLACE DELAYED INTO t (c) VALUES (1);
ALTER TABLE t MODIFY c FLOAT NOT NULL;

CREATE TABLE t1 (pk INT PRIMARY KEY) ENGINE=MEMORY;
INSERT INTO t1 VALUES (1),(2);
FLUSH STATUS; # not needed for the test case, only for cleanup
REPLACE DELAYED INTO t1 VALUES (1);CREATE TABLE t1 (pk INT PRIMARY KEY) ENGINE=MEMORY;
