USE test;
CREATE TABLE t (a BLOB) ENGINE=InnoDB;
INSERT INTO t VALUES ('a');
ALTER TABLE t ADD COLUMN (c INT GENERATED ALWAYS AS (a+1) VIRTUAL), ADD INDEX idx1 (c);
ALTER TABLE t ADD d INT, ALGORITHM=INPLACE;
