CREATE TABLE t (a INT);
INSERT DELAYED INTO t VALUES(1);
ALTER TABLE t AUTO_INCREMENT=1;

CREATE TABLE t1 (pk INT PRIMARY KEY) ENGINE=InnoDB;
ALTER TABLE t1 ADD CHECK (b <= 1);
COMMIT RELEASE;
ALTER TABLE t1 AUTO_INCREMENT=1;
