USE test;
SET SQL_MODE='';
CREATE TABLE t (v1 VARCHAR (255) AS (c1) PERSISTENT, c1 VARCHAR(50)) COLLATE=latin1_general_ci ENGINE=MyISAM;
INSERT INTO t VALUES(1,0xff00fef0);
CHECKSUM TABLE t EXTENDED;

USE test;
SET SQL_MODE='';
CREATE TABLE t (a BLOB, b BLOB GENERATED ALWAYS AS (a) VIRTUAL) ENGINE=MyISAM;
INSERT INTO t values (1,1),(2,2);
CHECKSUM TABLE t;
