USE test;
CREATE TABLE t (c INT);
SELECT JSON_ARRAYAGG(TRUE) FROM t;

SELECT JSON_ARRAYAGG(1) FROM t;  # Same result

SELECT JSON_ARRAYAGG(0) FROM t;  # Same result

USE test;
CREATE TEMPORARY TABLE t0(a INT) ENGINE=InnoDB;
SELECT 0x0=JSON_ARRAYAGG(a) FROM t0;
