INSTALL SONAME 'ha_rocksdb';
CREATE TABLE t1 (pk INT PRIMARY KEY, a INT) ENGINE=RocksDB;
INSERT INTO t1 VALUES (1,1),(2,1);
ALTER TABLE t1 ADD UNIQUE (a) COMMENT 'foo';
CREATE TABLE t2 (b INT) ENGINE=RocksDB;
DROP TABLE t2;
SELECT 1;
