USE test;
CREATE TABLE t1(a DATETIME);
CREATE TABLE t2(a VARCHAR(20));
SELECT (SELECT CONCAT(a),1 FROM t1) <=> (SELECT CONCAT(a),1 FROM t2);

USE test;
CREATE TEMPORARY TABLE t(a VARCHAR(20) NOT NULL, b VARCHAR(20));
ALTER TABLE t MODIFY a DATETIME;
INSERT INTO t VALUES (1, ST_GEOMFROMTEXT('abcdefghijklmnopqrstuvwxyz'));
CREATE TEMPORARY TABLE t2 (a VARCHAR(20), b VARCHAR(20), c VARCHAR(20)) ENGINE=MEMORY;
INSERT INTO t VALUES (45199,1184);#ERROR: 1114 - Tabulka 'abcdefghijklmnopqrstuvwxyz' je pln�
SET NAMES cp850;
SELECT (SELECT CONCAT(a),1 FROM t) <=> (SELECT CONCAT(a),1 FROM t2);
