USE test;
SET SQL_MODE='';
SET SESSION max_heap_table_size=1;
CREATE TABLE t(a INT,b DOUBLE,c INT,KEY i(b,a)) PARTITION BY HASH(c) PARTITIONS 3;
INSERT INTO t VALUES(0,0,0);
INSERT INTO t(b)VALUES (REPEAT(0,0)),(REPEAT(0,0)),(REPEAT(0,0));
SELECT a FROM t WHERE a NOT IN (SELECT a FROM t);
