CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT  INTO t1 VALUES (1),(2),(3),(4),(5),(6);
CREATE TABLE t2 (f BLOB UNIQUE) ENGINE=InnoDB WITH SYSTEM VERSIONING PARTITION BY system_time INTERVAL 1 WEEK (PARTITION p1 HISTORY, PARTITION pn CURRENT);
INSERT INTO t2 VALUES (NULL),('');
DELETE t2.* FROM t1, t2;
