USE test;
SET SQL_MODE='';
CREATE TABLE t1(pk INT PRIMARY KEY) ENGINE=Aria;
SELECT * FROM t1 WHERE a IS NULL OR a > 0;
CREATE TEMPORARY TABLE t3 (c1 INT NOT NULL) ENGINE=Aria;
DELETE a3,a2 FROM t2 AS a1 INNER JOIN t3 AS a2, t3 AS a3;
REPAIR TABLE t1, t2, t3;
INSERT INTO t3 SELECT * FROM t3;
