USE test;
CREATE TABLE t(a INT,b INT) ENGINE=MEMORY;
INSERT INTO t SET a=1;
SELECT JSON_ARRAYAGG(b LIMIT 2) FROM t;

USE test;
CREATE TABLE t1(a INT,b INT,KEY(a)) ENGINE=MEMORY;
SELECT EVENT_NAME,COUNT_STAR FROM performance_schema.events_waits_summary_global_by_event_name WHERE EVENT_NAME LIKE NULL;
INSERT INTO t1 SET a=3;
SELECT JSON_ARRAYAGG(b LIMIT 2)FROM t1;
