CREATE DATABASE db CHARACTER SET utf32;
SET SESSION SESSION_TRACK_TRANSACTION_INFO= CHARACTERISTICS;
USE db;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;

SET SESSION_TRACK_TRANSACTION_INFO=CHARACTERISTICS;
SET SESSION COLLATION_DATABASE=utf32_general_ci;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION WITH CONSISTENT SNAPSHOT;
