USE test;
SET SQL_MODE='';
SET optimizer_switch='subquery_cache=off';
CREATE TABLE t1 (a INT,b INT);
INSERT INTO t1 VALUES (0,0),(0,0);
SELECT (SELECT DISTINCT 1 FROM t1 t1i GROUP BY t1i.a ORDER BY MAX(t1o.b)) FROM t1 AS t1o;
CREATE PROCEDURE p1(min INT,max INT) BEGIN DECLARE DONE INT DEFAULT FALSE;
