USE test;
CREATE TABLE t(i INT KEY,f INT) ENGINE=InnoDB;
INSERT INTO t VALUES (1,1);
ALTER TABLE t ADD COLUMN c1 BIGINT UNSIGNED AS ROW START INVISIBLE, 
              ADD COLUMN c2 BIGINT UNSIGNED AS ROW END INVISIBLE, 
              ADD PERIOD FOR SYSTEM_TIME(c1,c2), 
              ADD SYSTEM VERSIONING;
START TRANSACTION WITH CONSISTENT SNAPSHOT;
INSERT INTO t VALUES (7,0),(6,0),(5,0),(4,0),(3,0),(2,0),(100,0);
DELETE FROM t;
INSERT INTO t VALUES (0,0);
DELETE FROM t;
