USE test;
CREATE TEMPORARY TABLE t(a INT);
ALTER TABLE t ADD c0 INT;
ALTER TABLE t ADD CONSTRAINT CHECK(c0 NOT IN (0,0,0));
ALTER TABLE t ADD c0 BLOB;
INSERT INTO t VALUES(0,0),(0,0),(0,0),(0,0),(0,0),(0,0),(0,0);
