CREATE TABLE t1 (a TIME NOT NULL);
CREATE VIEW v1 AS SELECT * FROM t1;
SET SQL_MODE= 'ONLY_FULL_GROUP_BY';
SELECT ROUND(a), COUNT(*) FROM v1;

# MDEV-21797
CREATE TABLE t1 (a time not null) engine=innodb;
SELECT STD(0) FROM t1 ORDER BY ROUND(a);
