# mysqld options required for replay: --log-bin
SET SQL_MODE='';
SET SESSION binlog_format=1;
CREATE TABLE t (a INT);
LOCK TABLES t WRITE;
CREATE OR REPLACE TABLE t (c INT DEFAULT NULL, ROW_START BIGINT UNSIGNED GENERATED ALWAYS AS ROW START INVISIBLE, ROW_END BIGINT UNSIGNED GENERATED ALWAYS AS ROW END INVISIBLE, PERIOD FOR SYSTEM_TIME (ROW_START, ROW_END)) WITH system VERSIONING;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
INSERT INTO t (c) VALUES (1);
