SET GLOBAL aria_encrypt_tables= 1;
CREATE TABLE t1 (pk INT PRIMARY KEY, a INT, KEY(a)) ENGINE=Aria TRANSACTIONAL=1;
ALTER TABLE t1 DISABLE KEYS;
INSERT INTO t1 VALUES  (1,1);
ALTER TABLE t1 ENABLE KEYS;

USE test;
CREATE TABLE t(c1 INT,KEY(c1))ENGINE=InnoDB;
INSERT INTO t VALUES(55997),(3942);
ALTER TABLE t ENGINE=Aria;
SET GLOBAL aria_encrypt_tables=1;
REPAIR TABLE t USE_FRM;
REPAIR TABLE t USE_FRM;

USE test;
SET GLOBAL aria_encrypt_tables=1;
CREATE TABLE t1(id int,key GEN_CLUST_INDEX(id))engine=Aria;
INSERT INTO t1 SELECT timediff(timestamp'2008-12-31 23:59:59.000001',timestamp'2008-12-30 01:01:01.000002');
# Then shutdown server

USE test;
SET GLOBAL table_open_cache=FALSE;
SET default_storage_engine=Aria;
SET GLOBAL aria_encrypt_tables=ON;
CREATE TABLE t(GRADE DECIMAL PRIMARY KEY);
INSERT INTO t VALUES(0);
CREATE TEMPORARY TABLE t SELECT 1 f1;
CREATE USER a@localhost IDENTIFIED WITH '';
DROP TABLE t,t2;
ANALYZE NO_WRITE_TO_BINLOG TABLE t;

USE test;
SET SQL_MODE='';
CREATE TABLE t2(a INT KEY) ROW_FORMAT=REDUNDANT;
SET GLOBAL aria_encrypt_tables=ON;
CREATE TABLE t1(c1 DECIMAL KEY,c2 DECIMAL) ENGINE=Aria;
INSERT INTO t1 VALUES(0,x'');
DROP TABLES t1,t2;

USE test;
SET SQL_MODE='';
SET GLOBAL aria_encrypt_tables=1;
CREATE TABLE t1 (c1 INT PRIMARY KEY) ENGINE=Aria;
INSERT INTO t1 VALUES (1);
CREATE TRIGGER t1_ai AFTER INSERT ON t1 FOR EACH ROW SET @a:='a';
