CREATE OR REPLACE TABLE t1 (f TEXT UNIQUE, FULLTEXT(f)) ENGINE=InnoDB;
INSERT INTO t1 VALUES ('foo');
CREATE OR REPLACE TABLE t2 (a VARCHAR(255)) ENGINE=InnoDB;
INSERT INTO t2 VALUES ('foobar'),('qux');
UPDATE t1 JOIN t2 SET f = a;
