USE test;
CREATE TABLE t (a CHAR(198));
ALTER TABLE t CHANGE COLUMN a a CHAR(220) BINARY;
ALTER TABLE t ADD COLUMN b INT FIRST;

CREATE TABLE t1 (a TEXT CHARSET utf8, b INT) ENGINE=InnoDB CHARSET utf8mb4;
ALTER TABLE t1 MODIFY a TEXT AFTER b;
