USE test;
CREATE TEMPORARY TABLE t3 (c1 INT, INDEX(c1)) UNION=(t1,t2) ENGINE=InnoDB;
CREATE TABLE t2 (c1 INT, c2 INT) ENGINE=InnoDB;
CREATE TABLE t1 (a INT NOT NULL, b INT NOT NULL, pk INT NOT NULL, PRIMARY KEY (pk), KEY(a), KEY(b)) ENGINE=InnoDB PARTITION BY HASH(pk) PARTITIONS 10;
REPAIR TABLE t1, t2, t3;
