USE test;
CREATE TABLE t(a CHAR BINARY) ENGINE=InnoDB;
ALTER TABLE t CHANGE COLUMN a a CHAR(20);

USE test;
CREATE TABLE t (c CHAR(10) BINARY) ENGINE=InnoDB;
ALTER TABLE t CHANGE COLUMN c a CHAR(11);
