USE test;
CREATE TEMPORARY TABLE t(c INT) ENGINE=InnoDB;
LOCK TABLES t AS a WRITE;
ALTER TABLE t ADD COLUMN c2 INT;
REPAIR TABLE t USE_FRM;

USE test;
CREATE TABLE t (a INT PRIMARY KEY, b INT);
SET MAX_STATEMENT_TIME=0.001;
LOCK TABLE t WRITE;
ALTER TABLE t ALGORITHM=INPLACE, ADD d FLOAT;

CREATE DATABASE test;
USE test;
CREATE TEMPORARY TABLE t (c1 INT) ENGINE=InnoDB;
LOCK TABLES t AS a READ, t AS b READ LOCAL;
OPTIMIZE LOCAL TABLE t;
REPAIR LOCAL TABLE t USE_FRM;
