USE test;
CREATE TABLE t1 (f1 INT) ENGINE=Aria;
CREATE TABLE t2 (f2 INT) ENGINE=Aria;
LOCK TABLES t2 WRITE, t1 WRITE;
INSERT INTO t1 VALUES (1);
CREATE TRIGGER ai AFTER INSERT ON t1 FOR EACH ROW UPDATE t1 SET v=1 WHERE b=new.a;
UNLOCK TABLES;

# Further testcases may not be deterministic 
DROP DATABASE test;CREATE DATABASE test;USE test;
SET SQL_MODE='';
SET SESSION storage_engine=Aria;
CREATE TABLE t3 (c1 DATE,c2 NUMERIC(65) UNSIGNED ZEROFILL,c3 DECIMAL(2)) ENGINE=Aria;
CREATE TABLE t2 (c1 VARCHAR(100)) ENGINE=Aria;
CREATE TABLE t1 (c1 INTEGER);
LOCK TABLES t3 WRITE,t2 WRITE,t1 WRITE;
INSERT INTO t1 VALUES (CONVERT(_ucs2 0x062C064706270646 USING utf8));
CREATE TRIGGER ai AFTER INSERT ON t1 FOR EACH ROW UPDATE t1 SET v=1 WHERE b=new.a;
INSERT INTO t1 VALUES (CONVERT(_ucs2 0x062C064706270646 USING utf8));
DROP DATABASE test;CREATE DATABASE test;USE test;
SET SQL_MODE='';
SET SESSION storage_engine=Aria;
CREATE TABLE t3 (c1 DATE,c2 NUMERIC(65) UNSIGNED ZEROFILL,c3 DECIMAL(2)) ENGINE=Aria;
CREATE TABLE t2 (c1 VARCHAR(100)) ENGINE=Aria;
CREATE TABLE t1 (c1 INTEGER);
LOCK TABLES t3 WRITE,t2 WRITE,t1 WRITE;
INSERT INTO t1 VALUES (CONVERT(_ucs2 0x062C064706270646 USING utf8));
CREATE TRIGGER ai AFTER INSERT ON t1 FOR EACH ROW UPDATE t1 SET v=1 WHERE b=new.a;
INSERT INTO t1 VALUES (CONVERT(_ucs2 0x062C064706270646 USING utf8));

DROP DATABASE test; CREATE DATABASE test; USE test;
SET default_storage_engine=InnoDB;
CREATE FUNCTION char not null(f1 char not null) returns char not null return f1;
CREATE TABLE t1 (c1 DECIMAL(1,1) PRIMARY KEY,c2 DECIMAL(40,30) UNSIGNED,c3 MEDIUMINT(1) ZEROFILL) ENGINE=Aria;
LOCK TABLES mysql.time_zone READ, mysql.proc READ, t1 WRITE;
SET @@global.max_statement_time = 0.123456;
INSERT INTO t1  (c1,c2,c3) VALUES ('a','a',8), ('a','a',2), ('a','b',3), ('a','c',4), ('a','d',5);
select insert('hello', -1, 1, 'hi');
CREATE TRIGGER t_after_insert AFTER INSERT ON t1 FOR EACH ROW SET @bug42188 = 10;
UNLOCK TABLES;
SELECT SLEEP(5);

DROP DATABASE transforms;
CREATE DATABASE transforms;
USE test;
select 1 FROM t1  order by t1.b;
SET @@SESSION.OPTIMIZER_SWITCH="subquery_cache=OFF";
SET @@SESSION.OPTIMIZER_SWITCH="index_merge_intersection=ON";
set session default_storage_engine='Aria';
SET @@GLOBAL.OPTIMIZER_SWITCH="use_index_extensions=ON";
INSERT INTO t3 VALUES(NULL,1,2,3,4,5,6);
SET @@GLOBAL.OPTIMIZER_SWITCH="mrr_sort_keys=ON";
SET @@SESSION.OPTIMIZER_SWITCH="derived_with_keys=ON";
CREATE TABLE t1(a INT, KEY (a)) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=1 ENGINE=RocksDB;
CREATE TABLE t1( a VARCHAR(65532) COLUMN_FORMAT COMPRESSED ) ROW_FORMAT = COMPRESSED ENGINE=RocksDB;
lock TABLE t1 write, mysql.event read;
insert into t2 values (53698);
insert into t1 values ('a'),('a ');
SELECT @@log_warnings = @@global.log_warnings;
SET @@SESSION.OPTIMIZER_SWITCH="condition_pushdown_from_having=OFF";
SET @@SESSION.OPTIMIZER_SWITCH="index_merge_sort_union=ON";
SET GLOBAL innodb_monitor_reset='buffer_flush_avg_time';
CREATE TABLE t1 (c1 VARCHAR(10));
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW INSERT INTO t1  VALUES (NEW.i);
CREATE TABLE t1 (c1 varchar(100)) ENGINE=TokuDB;
UNLOCK TABLES;
UNLOCK TABLES;
UNLOCK TABLES;
UNLOCK TABLES;
UNLOCK TABLES;
UNLOCK TABLES;
SELECT 1;
SELECT SLEEP(5);

# mysqld options required for replay: --log-bin --sql_mode=ONLY_FULL_GROUP_BY --max_allowed_packet=33554432 --maximum-bulk_insert_buffer_size=1M --maximum-join_buffer_size=1M --maximum-max_heap_table_size=1M --maximum-max_join_size=1M --maximum-myisam_max_sort_file_size=1M --maximum-myisam_mmap_size=1M --maximum-myisam_sort_buffer_size=1M --maximum-optimizer_trace_max_mem_size=1M --maximum-preload_buffer_size=1M --maximum-query_alloc_block_size=1M --maximum-query_prealloc_size=1M --maximum-range_alloc_block_size=1M --maximum-read_buffer_size=1M --maximum-read_rnd_buffer_size=1M --maximum-sort_buffer_size=1M --maximum-tmp_table_size=1M --maximum-transaction_alloc_block_size=1M --maximum-transaction_prealloc_size=1M --log-output=none
USE test;
SET @@SESSION.OPTIMIZER_SWITCH="mrr_sortks=ON";
create or replace table t1 (f1 int,key(f1)) engine=Aria;
LOCK TABLES mysql.time_zone READ,mysql.proc READ,t1 WRITE;
INSERT INTO t1 VALUES(''),(''),('až'),('cčc'),('ggᵷg'),('¢¢');
CREATE TRIGGER tr1 BEFORE INSERT ON t1 FOR EACH ROW SET @aux = 1;
UNLOCK TABLES; ;
UNLOCK TABLES; ;
