# mysqld options required for replay:  --sql_mode=
USE test;
SET @@SESSION.sort_buffer_size=200;
CREATE TEMPORARY TABLE t1(c1 CHAR(2) PRIMARY KEY,c2 INT ZEROFILL);
CREATE TEMPORARY TABLE t2(c1 CHAR(255) PRIMARY KEY,c2 CHAR (255));
INSERT INTO t1 VALUES(0,0);
INSERT INTO t1 VALUES('aaa',0);
INSERT INTO t2 VALUES('aaa',0);
INSERT INTO t2 SELECT * FROM t1;
DELETE FROM b,c USING t2 AS a JOIN t1 AS b JOIN t2 AS c;
