CREATE TABLE t1 (FTS_DOC_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, c TINYTEXT, PRIMARY KEY (FTS_DOC_ID), FULLTEXT KEY (c)) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1,'txt');
UPDATE t1 SET FTS_DOC_ID = 4294967298;

CREATE TABLE t1 (FTS_DOC_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, c TINYTEXT, PRIMARY KEY (FTS_DOC_ID), FULLTEXT KEY (c)) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1,'txt');
UPDATE t1 SET FTS_DOC_ID = 197505260223;
SET @innodb_optimize_fulltext_only.save= @@innodb_optimize_fulltext_only;
SET GLOBAL innodb_optimize_fulltext_only = 1;
OPTIMIZE TABLE t1;

SET @@session.insert_id = 100000000000;
CREATE TABLE t (FTS_DOC_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, c TEXT) ENGINE=InnoDB;
INSERT INTO t (c) VALUES ('aaa');
CREATE FULLTEXT INDEX i ON t (c);
