USE test;
CREATE TABLE t (a INT PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO t VALUES (2);
SELECT a % 2 AS i, JSON_OBJECTAGG(a,a) FROM t GROUP BY i;

CREATE TABLE t (e INTEGER, a VARCHAR(255), v VARCHAR(255));
INSERT INTO t VALUES (0, 'a1', '1'), (0, 'a2', '2'), (1, 'b1', '3');
SELECT e, JSON_OBJECTAGG(a, v) FROM t GROUP BY e;
