USE test;
SET SQL_MODE='';
SET GLOBAL innodb_limit_optimistic_insert_debug=2;
CREATE TABLE t (a INT) ENGINE=InnoDB;
ALTER TABLE t ADD COLUMN b INT FIRST;
INSERT INTO t VALUES (5,7),(8,9),(4,1);
DELETE FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;  # Will likely crash on this one
SELECT GROUP_CONCAT(a) FROM t;  # Or on this one
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
SELECT GROUP_CONCAT(a) FROM t;
