USE test;
CREATE TABLE t1 (pk INT, f GEOMETRY NOT NULL, PRIMARY KEY (pk), UNIQUE KEY (f(8))) ENGINE=InnoDB;
ALTER TABLE t1 DROP PRIMARY KEY;
INSERT INTO t1 VALUES (1, GEOMFROMTEXT('POINT(1 1)'));
SELECT * FROM t1 ORDER BY pk;
