CREATE TABLE t1 (a CHAR(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL) ENGINE=InnoDB;
INSERT INTO t1 VALUES ('foo');
ALTER TABLE t1 MODIFY a CHAR(6);

CREATE DATABASE test;
USE test;
CREATE TABLE t (a BLOB NOT NULL, b DATE NOT NULL);
ALTER TABLE t CHANGE COLUMN a a CHAR(150) BINARY;
INSERT INTO t VALUES (1261,0);
ALTER TABLE t CHANGE COLUMN a a CHAR(200) NOT NULL;
