# mysqld options required for replay: --log-bin 
SET GLOBAL ARIA_GROUP_COMMIT=HARD;
XA START 'A';
SET GLOBAL ARIA_CHECKPOINT_LOG_ACTIVITY=1;
SET GLOBAL ARIA_GROUP_COMMIT_INTERVAL=1000000000;
DELETE FROM mysql.tables_priv WHERE USER LIKE '_%';

USE test;
SET GLOBAL ARIA_CHECKPOINT_LOG_ACTIVITY = 254;
SET GLOBAL ARIA_GROUP_COMMIT=hard;
SET GLOBAL ARIA_GROUP_COMMIT_INTERVAL=1000000000;
CREATE ROLE a;
CREATE PROCEDURE p1() BEGIN END;
