USE test;
SET SQL_MODE='';
SET GLOBAL innodb_prefix_index_cluster_optimization=1;
CREATE TABLE t(c POINT GENERATED ALWAYS AS (POINT(1,1)) UNIQUE) ENGINE=InnoDB;
INSERT t SET c=1;
INSERT INTO t SELECT * FROM t WHERE c > (SELECT MAX(c) FROM t);

USE test;
SET GLOBAL innodb_prefix_index_cluster_optimization = 1;
CREATE TABLE t1(c INT, p POINT, KEY(p)) ENGINE=InnoDB;
INSERT INTO t1 VALUES (103, ST_POINTFROMTEXT('POINT(1 1)'));
SELECT ST_ASTEXT(p) FROM t1 WHERE p = ST_POINTFROMTEXT('POINT(1 1)');
