CREATE TABLE t1 (a TEXT, FULLTEXT INDEX (a));
SET SESSION sql_select_limit=0;
SELECT (SELECT 1 FROM (SELECT 1) f WHERE MATCH (a) AGAINST ('')) FROM t1;

SET SESSION sql_select_limit=0;
CREATE TABLE t (c TEXT CHARACTER SET utf8mb4, FULLTEXT INDEX (c));
SELECT (SELECT 1 FROM (SELECT 1) AS s WHERE MATCH (c) AGAINST ('')) FROM t;
