USE test;
CREATE TABLE t(c INT, c2 GEOMETRY NOT NULL, c3 GEOMETRY NOT NULL);
PREPARE p FROM "UPDATE t SET b = 1";

CREATE OR REPLACE TABLE t1(c INT, c2 INT NOT NULL, c3 INT NOT NULL);
PREPARE p FROM "UPDATE t SET b = 1";
