perl t\gensql.t
perl t\gensql.yy
perl t\gentest.t
perl t\grammar-doubledefine.t.disabled
perl t\grammar-doubledefine.yy
perl t\grammar.t
perl t\prng.t
perl t\simplify-empty.t
perl t\simplify-empty.yy
perl t\simplify-grammar.t
perl t\simplify-grammar.yy
