Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.network "forwarded_port", guest: 5432, host: 5434
  config.vm.provision "shell", path: "provision.sh",
    env: {
      "PG_VERSION" => ENV['PG_VERSION'],
      "PG_MAJOR" => ENV['PG_MAJOR']
    }
end

