# Vagrantfile for Ubuntu 22.04 (ubuntu22/Vagrantfile)
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 5432, host: 5437
  config.vm.provision "shell", path: "provision.sh",
    env: {
      "PG_VERSION" => ENV['PG_VERSION'],
      "PG_MAJOR" => ENV['PG_MAJOR']
    }
end
