#!/bin/bash
# Created by Roel Van de Paar, MariaDB
# Note: use ~/mariadb-qa/mass_bug_report.sh from a dbg basedir to process testcases in /test/TESTCASES

TARGET=~/mariadb-qa/testcase-scripts
mkdir -p ${TARGET}
SCRIPT_PWD="$(cd `dirname $0` && pwd)"

cd ${SCRIPT_PWD}
cp mvknown ${TARGET}
cp mysql_scan ${TARGET}
cp scan ${TARGET}
cp scan_nojson_count ${TARGET}
cp old_bugs_move ${TARGET}
cp backup_github ${TARGET}
cp gen_inprogress ${TARGET}
cp optimizer_bugs ${TARGET}
cp temp_move_away ${TARGET}
cp move_nocore_back ${TARGET}
cp move_long ${TARGET}

cd ${TARGET}
git add *
cd ~/mariadb-qa/BUGS
git add *
