#!/bin/bash
mkdir -p MORE_THEN_100_LINES
if [ -d ./MORE_THEN_100_LINES ]; then
  wc -l *.sql | sort -n | grep -v total | grep "^[0-9 ][0-9 ][0-9 ][0-9 ][0-9 ][0-9]" | sed 's|.* ||' | sed 's|\.sql||' | xargs -I{} echo "mv {}.* MORE_THEN_100_LINES" | xargs -I{} bash -c "{}" 
else 
  echo "Assert: dir creation failed"
fi
