$combinations = [
	['
		--grammar=conf/engines/engine_stress.yy
		--gendata=conf/engines/engine_stress.zz
		--queries=1M
		--engine=Maria
		--mysqld=--log-output=file
	'],[
		'--reporters=ErrorLog,Backtrace,Recovery,Shutdown',
		'--reporters=ErrorLog,Backtrace,Recovery,Shutdown',
		'--reporters=ErrorLog,Backtrace,Recovery,Shutdown',
		'--reporters=ErrorLog,Backtrace,DatabaseConsistency,Shutdown'
	],[
		'--duration=30',
		'--duration=120',
		'--duration=240',
		'--duration=360'
	],[
		'--threads=1',
		'--threads=5',
		'--threads=10',
		'--threads=20'
	],[
		'--rows=1',
		'--rows=10',
		'--rows=100',
		'--rows=1000',
		'--rows=10000',
		'--rows=100000',
	],[
		'--mask-level=0',
		'--mask-level=1',
		'--mask-level=2'
	],[
		'',
		'--mysqld=--maria-repair-threads=2'
	],[
		'--mysqld=--maria-group-commit=soft',
		'--mysqld=--maria-group-commit=hard'
	],[
		'--mysqld=--maria_group_commit_interval=0',
		'--mysqld=--maria_group_commit_interval=1',
		'--mysqld=--maria_group_commit_interval=10',
		'--mysqld=--maria_group_commit_interval=100'
	],[
		'--mysqld=--maria-checkpoint-interval=0',
		'--mysqld=--maria-checkpoint-interval=1',
		'--mysqld=--maria-checkpoint-interval=120'
	],[
		'--mysqld=--maria-block-size=1K',
		'--mysqld=--maria-block-size=4K',
		'--mysqld=--maria-block-size=16K'
	]
];
