#!/bin/bash

rm -f report.log
if [ -r report.log ]; then echo "Assert: report.log still present though this script tried to delete it!"; exit 1; fi

export TEXT=
MYEXTRA_OPT=
if [ "${1}" == "ASAN" ]; then
  export TEXT="${2}"
  # The following used statement has limitations, but the one on the next line did not work, likely due to sed limitations.
  # MYEXTRA_OPT="$(echo "${MYEXTRA_OPT}" | sed 's|ASAN||;s|${TEXT}||')"
  MYEXTRA_OPT="$3 $4 $5 $6 $7 $8 $9"
  ~/mariadb-qa/bug_report.sh ASAN "${MYEXTRA_OPT}" | tee report.log
else
  MYEXTRA_OPT="$*"
  sed -i 's|^TEXT="[^"]\+"|TEXT=""|' ~/mariadb-qa/bug_report.sh  # Ensure we're looking for core files, not specific bugs for which bug_report.sh may have been updated
  ~/mariadb-qa/bug_report.sh "${MYEXTRA_OPT}" | tee report.log
  ~/tt | grep -A1 "URL"
fi
