#!/bin/bash
SCRIPT_PWD=$(cd "`dirname $0`" && pwd)
cd ${SCRIPT_PWD}
./backup_github
/test/backup_github
/test/TESTCASES/backup_github
cd ~/mariadb-qa/BUGS
git add *
cd ~/mariadb-qa/homedir_scripts
git add *
