#!/bin/bash
set +H
if [ "${1}" != "REVERSE" ]; then  # Standard search (show the string if it exists)
  grep --binary-files=text -Fi "$*" ~/mariadb-qa/known_bugs.strings
else  # Reverse search (show the string if it does not exist yet)
  SEARCH="$(echo "$*" | sed 's|REVERSE[ \t]*||')"
  if [ -z "$(grep --binary-files=text -Fi "${SEARCH}" ~/mariadb-qa/known_bugs.strings)" ]; then
    echo "${SEARCH}"
  fi
fi
