#!/bin/bash
# Also see ~/mariadb-qa/memory_leaks_howto.txt for related throubleshooting info, otherwise unrelated to the monitoring script below

# User variables
KILL_LARGE=1  # Will kill any process consuming more then KILL_PERCENT percent of memory
KILL_PERCENT=3

# Script variables
while true; do
  clear
  ps --sort -rss -eo pid,pmem,rss,vsz,comm | head -n15
  HEADLINE=;PERCENT=;PID=
  if [ "${KILL_LARGE}" -eq 1 ]; then
    HEADLINE="$(ps --sort -rss -eo pid,pmem,rss,vsz,comm | head -n2 | tail -n1)"
    PERCENT="$(echo ${HEADLINE} | awk '{print $2}' | sed 's|\.[0-9]\+||;s|[ \t]||g')"
    PID="$(echo ${HEADLINE} | awk '{print $1}' | sed 's|[ \t]||g')"
    if [ ${PERCENT} -gt ${KILL_PERCENT} ]; then
      echo "Process ${PID} is consuming too much memory (${PERCENT}%): terminating..."
      kill -9 ${PID}
      kill -9 ${PID}
      kill -9 ${PID}
      sleep 2  # Allows user to notice/read message
    fi
  fi
  sleep 3
done
