#!/bin/bash
# Also see ~/mariadb-qa/memory_leaks_howto.txt for related throubleshooting info, otherwise unrelated to the monitoring script below
PROCESS=
MEMORY=
TOO_MUCH_MEM=
while true; do
  clear
  ps --sort -rss -eo pid,pmem,rss,vsz,comm | head -n15
  TOO_MUCH_MEM="$(ps --sort -rss -eo pid,pmem,rss,vsz,comm | grep -E "mysqld|pquery2" | head -n1 | grep -o " *[0-9]\+ *[4-9][0-9]\.")"
  if [ "${TOO_MUCH_MEM}" != "" ]; then
    PROCESS="$(echo "${TOO_MUCH_MEM}" | sed 's|^ *||' | sed 's| .*||' | sed 's| ||g')"
    MEMORY="$(echo "${TOO_MUCH_MEM}" | sed 's|^ *||' | sed 's|.* ||' | sed 's| ||g')"
    echo "Process ${PROCESS} is consuming too much memory (${TOO_MUCH_MEM}%): terminating..."
    kill -9 ${PROCESS}
    PROCESS=
    MEMORY=
    TOO_MUCH_MEM=
    sleep 2  # Allows user to notice/read message
  fi
  sleep 3
done
