#!/bin/bash
# Also see ~/mariadb-qa/memory_leaks_howto.txt for related throubleshooting info, otherwise unrelated to the monitoring script below

# User variables
KILL_LARGE=1    # Will kill any process consuming equal to or more then KILL_PERCENT.0 percent of memory
KILL_PERCENT=4  # Ex: 4: All processes up to 3.99 will continue to live, 4.00 and onwards will be killed

# Script variables
while true; do
  clear
  ps --sort -rss -eo pid,pmem,rss,vsz,comm | head -n7
  HEADLINE=;PERCENT=;PID=
  if [ "${KILL_LARGE}" -eq 1 ]; then
    HEADLINE="$(ps --sort -rss -eo pid,pmem,rss,vsz,comm | head -n2 | tail -n1)"
    PERCENT="$(echo ${HEADLINE} | awk '{print $2}' | sed 's|\.[0-9]\+||;s|[ \t]||g')"
    PID="$(echo ${HEADLINE} | awk '{print $1}' | sed 's|[ \t]||g')"
    if [ ${PERCENT} -ge ${KILL_PERCENT} ]; then
      echo "Process ${PID} is consuming too much memory (${PERCENT}%): terminating..."
      kill -9 ${PID}
      kill -9 ${PID}
      kill -9 ${PID}
      sleep 2  # Allows user to notice/read message
    fi
  fi
  echo ''
  echo -e "USER\tTTY\tJCPU\tPCPU\tCOMMAND"
  w -h | awk '{print $1"\t"$2"\t"$6"\t"$7"\t"$8" "$9" "$10" "$11" "$12" "$13" "$14" "$15" "$16" "$17" "$18" "$19" "$20}' | grep -E '[0-9][0-9]\.[0-9][0-9]s|[0-9]:[0-9][0-9]m' | grep -v 'sleep' | grep -v 'awk'
  sleep 4
done
