#!/bin/bash
BASEDIR=/test/MD...
if [ ! -r ${BASEDIR} ]; then echo "BASEDIR (${BASEDIR}) does not exist!"; exit 1; fi
cd $BASEDIR
vi start
./all
./stop
echo "vi log/master.err"
echo "gdb bin/mysqld $(ls data/core* 2>/dev/null)"
