#!/bin/bash
# Created by Roel Van de Paar, Percona LLC

ls_exec(){
  ls -ld [0-9]* | sed 's|.*..:.. ||' | sort | xargs -I{} echo 'wc -l ${PWD}/{}/*/*.sql_out* ${PWD}/{}/*/*/*.sql_out* ${PWD}/{}/*/*/*/*.sql_out* 2>/dev/null' | xargs -I{} sh -c '{} | grep -vE "\.prev|total|subreducer" | sed "s|^[ ]*|   |"'
}

echo "Current testcases in /dev/shm:"
cd /dev/shm; OUT=$(ls_exec); echo $OUT | sed 's| \([0-9]\)|\n   \1|g;s|^|   |'

echo "Current testcases in /sda:"
cd /sda; ls_exec

if [ -r /tmp/pqr_status.cnt ]; then
  echo "New bugs found in this run: $(cat /tmp/pqr_status.cnt)"
fi
