#!/bin/bash
INPUT="${1}"
echo "Searching for '${1}' in various places... This may take a while!"
echo "1/8..."
grep --binary-files=text -Ei "${INPUT}" /test/*/*/log/master.err 2>/dev/null
echo "2/8..."
grep --binary-files=text -Ei "${INPUT}" /data/*/*/log/master.err 2>/dev/null
echo "3/8..."
grep --binary-files=text -Ei "${INPUT}" /test/*/*/MYBUG 2>/dev/null
echo "4/8..."
grep --binary-files=text -Ei "${INPUT}" /data/*/*/MYBUG 2>/dev/null
echo "5/8..."
grep --binary-files=text -Ei "${INPUT}" /test/*/log/master.err 2>/dev/null
echo "6/8..."
grep --binary-files=text -Ei "${INPUT}" /data/*/log/master.err 2>/dev/null
echo "7/8..."
grep --binary-files=text -Ei "${INPUT}" /test/TESTCASES/*.report 2>/dev/null
echo "8/8..."
grep --binary-files=text -Ei "${INPUT}" /data/TESTCASES/*.report 2>/dev/null
echo "Done!"
