#!/bin/bash
set +H
INPUT="${1}"
echo "Searching for '${INPUT}' in known bugs strings file..."
~/kbs "${INPUT}"
echo "Searching for '${INPUT}' in various places... This may take a while!"
echo "1/10..."
grep --binary-files=text -Ei "${INPUT}" /test/*/*/log/master.err 2>/dev/null
echo "2/10..."
grep --binary-files=text -Ei "${INPUT}" /data/*/*/log/master.err 2>/dev/null
echo "3/10..."
grep --binary-files=text -Ei "${INPUT}" /test/*/*/MYBUG 2>/dev/null
echo "4/10..."
grep --binary-files=text -Ei "${INPUT}" /data/*/*/MYBUG 2>/dev/null
echo "5/10..."
grep --binary-files=text -Ei "${INPUT}" /test/*/log/master.err 2>/dev/null
echo "6/10..."
grep --binary-files=text -Ei "${INPUT}" /data/*/log/master.err 2>/dev/null
echo "7/10..."
grep --binary-files=text -Ei "${INPUT}" /test/TESTCASES/*.report 2>/dev/null
echo "8/10..."
grep --binary-files=text -Ei "${INPUT}" /data/TESTCASES/*.report 2>/dev/null
echo "9/10..."
grep --binary-files=text -Ei "${INPUT}" /test/TESTCASES/*/*.report 2>/dev/null
echo "10/10..."
grep --binary-files=text -Ei "${INPUT}" /data/TESTCASES/*/*.report 2>/dev/null
echo "Done!"
