#!/bin/bash
OPTIONS="$(grep -i '^. mysqld options required for replay' "${1}" | head -n1 | sed "s|. mysqld options required for replay:[ \t]\+..sql_mode=[ \t]*$|SET SQL_MODE='';|")"
cat "${1}" | \
  sed 's|;#.*$|;|;s| ;$|;|g;s|;;$|;|g' | \
  sed 's|t1|t|g' | \
  sed 's|int|INT|gi;s|integer|INT|gi' | \
  sed 's|create|CREATE|gi' | \
  sed 's|table|TABLE|gi' | \
  sed 's|tables|TABLES|gi' | \
  sed 's|where|WHERE|gi' | \
  sed 's|set @@global\.|SET GLOBAL |gi' | \
  sed 's|set @@session\.|SET SESSION |gi' | \
  sed 's|use|USE|gi' | \
  sed 's|versioning|VERSIONING|gi' | \
  sed 's|trigger|TRIGGER|gi' | \
  sed 's|each|EACH|gi' | \
  sed 's|row|ROW|gi' | \
  sed 's|concat|CONCAT|gi' | \
  sed 's|after|AFTER|gi' | \
  sed 's|before|BEFORE|gi' | \
  sed 's|blob|BLOB|gi' | \
  sed 's|varchar|VARCHAR|gi' | \
  sed 's|char |CHAR |gi' | \
  sed 's|char(|CHAR(|gi' | \
  sed 's|character|CHARACTER|gi' | \
  sed 's|text|TEXT|gi' | \
  sed 's|replace|REPLACE|gi' | \
  sed 's|delayed|DELAYED|gi' | \
  sed 's|lock|LOCK|gi' | \
  sed 's|read|READ|gi' | \
  sed 's|write|WRITE|gi' | \
  sed 's|small|SMALL|gi' | \
  sed 's|large|LARGE|gi' | \
  sed 's|medium|MEDIUM|gi' | \
  sed 's|from|FROM|gi' | \
  sed 's|union|UNION|gi' | \
  sed 's|select|SELECT|gi' | \
  sed 's|update|UPDATE|gi' | \
  sed 's|insert|INSERT|gi' | \
  sed 's|delete|DELETE|gi' | \
  sed 's|truncate|TRUNACE|gi' | \
  sed 's|explain|EXPLAIN|gi' | \
  sed 's|extended|EXTENDED|gi' | \
  sed 's|repair|REPAIR|gi' | \
  sed 's|repeat|REPEAT|gi' | \
  sed 's|engine|ENGINE|gi' | \
  sed 's|temporary|TEMPORARY|gi' | \
  sed 's|replicate_do|REPLICATE_DO|gi' | \
  sed 's|order by|ORDER BY|gi' | \
  sed 's|drop|DROP|gi' | \
  sed 's|set|SET|gi' | \
  sed 's|bit|BIT|gi' | \
  sed 's|default|DEFAULT|gi' | \
  sed 's|session|SESSION|gi' | \
  sed 's|global|GLOBAL|gi' | \
  sed 's|primary|PRIMARY|gi' | \
  sed 's|key|KEY|gi' | \
  sed 's|null|NULL|gi' | \
  sed 's|not |NOT |gi' | \
  sed 's|linestring|LINESTRING|gi' | \
  sed 's|polygon|POLYGON|gi' | \
  sed 's|geometry|GEOMETRY|gi' | \
  sed 's| in | IN |gi' | \
  sed 's| on | ON |gi' | \
  sed 's| for | FOR |gi' | \
  sed 's|aria|Aria|gi' | \
  sed 's|memory|MEMORY|gi' | \
  sed 's|innodb|InnoDB|gi' | \
  sed 's|myisam|MyISAM|gi' | \
  sed 's|csv|CSV|gi' | \
  sed 's|archive|ARCHIVE|gi' | \
  sed 's|values|VALUES|gi' | \
  sed 's|\([^\.]\)st_|\1ST_|gi' | \
  sed 's|geomfromtext|GEOMFROMTEXT|gi' | \
  sed 's|ST_\([_a-zA-Z]\+\)|\UST_\1|gi' | \
  sed 's|row_format|ROW_FORMAT|gi' | \
  sed 's|key_block_size|KEY_BLOCK_SIZE|gi' | \
  sed 's|compressed|COMPRESSED|gi' | \
  sed 's|InnoDB_|innodb_|g' | \
  sed 's|GLOBAL_|global_|g' | \
  sed 's|into|INTO|gi' | \
  sed 's|threads|THREADS|gi' | \
  sed 's|unique|UNIQUE|gi' | \
  sed 's|innodb_random|INNODB_RANDOM|gi' | \
  sed 's|read_ahead|READ_AHEAD|gi' | \
  sed 's|innodb_limit_optimistic_insert_debug|INNODB_LIMIT_OPTIMISTIC_INSERT_DEBUG|gi' | \
  sed 's|innodb_file_per_TABLE|INNODB_FILE_PER_TABLE|gi' | \
  sed "s|^. mysqld options required for replay.*|${OPTIONS}|i" | \
  sed 's| [ \t]| |g'

#  sed 's|||gi' | \
